### ISSUE TITLE
feature request - ability to specify a class for the ul element

### ISSUE THREAD

**Issue by slawo-ch** [wyuenho/backgrid-paginator#22]
Specifying a class for the ul element makes it dead simple to integrate with bootstrap. Just make the class "pagination".

**Comment by philostler** [comment]
I'm working on a product where we need Bootstrap theming and I'm disappointed that consideration hasn't been taken for adding the `pagination` class into the ul element via the API as @slawo-ch asks. Our theming is meant to be a drop-&-drag Bootstrap theme experience... copying and pasting isn't an option for us. Sadly going to do a hack around for this
