### ISSUE TITLE
Double sorting grid:

### ISSUE THREAD

**Issue by oak-tree** [wyuenho/backgrid-paginator#37]
Hey there! great works!
I'm using 
`backbone.paginator`, `backgrid`, `backgrid-filter`, `backgrid-paginator`
it works great but i have one small issue when sorting by `column` at `server mode` it seems to :

first it fetches the sorted list ok but then it does another fetch of the first page. This result two fetches against server and the 2nd is unsorted. 

it seems that the second fetch comes from `backgrid-paginator` 

    self.listenTo(col, "backgrid:sorted", function () {
        if (self.goBackFirstOnSort) col.getFirstPage({reset: true});
      });
    },

maybe on `server mode` its better to try fetch the `first page` on sorting?

any ideas how to over come it ?

Thanks!

Oak

**Comment by foosbar** [comment]
@oak-tree, I think pull request 29 is what you're looking for? 

https://github.com/wyuenho/backgrid-paginator/pull/29

**Comment by oak-tree** [comment]
hey @foosbar ! yeap! that can work!
u would go father more and ask if its possible to do the request for sort to request the first page as well if 
`self.goBackFirstOnSort` is on

what do you think?

**Comment by wyuenho** [comment]
Fixed in #29
