### ISSUE TITLE
New release tag please

### ISSUE THREAD

**Issue by jsatk** [wyuenho/backgrid-paginator#38]
There have been several updates to this since the `0.3.5` release on January 21, 2014 13:45. Most notably one that removes the use of `hasNext` and `hasPrevious` in favor of `hasNextPage` and `hasPreviousPage`. Any chance we could get a release with these new updates?

**Comment by thorikawa** [comment]
+1

**Comment by grabcode** [comment]
+1

**Comment by nukkerone** [comment]
+10

**Comment by anaumidis** [comment]
+100

**Comment by philostler** [comment]
+1

**Comment by phillipsnick** [comment]
+1
