### ISSUE TITLE
Sorting caret disappears when changing page by using the arrows.

### ISSUE THREAD

**Issue by FredFaust** [wyuenho/backgrid-paginator#41]
You can reproduce the issue with the example found at : http://backgridjs.com/ref/extensions/paginator.html

It only happens when we change page by clicking on the pagination arrows, it works fine when changing page by clicking directly on a page number.

It might have some link with how the `getPage()` function is used when clicking a page number and that it is not called when clicking on the arrows. Take a look at this issue about this behavior : #17

**Comment by krosenberg** [comment]
It looks like the caret disappears if you don't pass `{reset:true}` in the fetch options. Looking at the code that handles the click (below), you can see that the only `get<whatever>Page()` that has `{reset:true}` is when you ask for a specific page, ie clicking on a page number. A solution would be to add `{reset:true}` to all of the `get<>Page()` arguments, but I'm not sure what the implications of that would be.
```
changePage: function (e) {
  e.preventDefault();
  var $el = this.$el, col = this.collection;
  if (!$el.hasClass("active") && !$el.hasClass("disabled")) {
    if (this.isRewind) col.getFirstPage();
    else if (this.isBack) col.getPreviousPage();
    else if (this.isForward) col.getNextPage();
    else if (this.isFastForward) col.getLastPage();
    else col.getPage(this.pageIndex, {reset: true});
  }
  return this;
}
```
