### ISSUE TITLE
ajax request with --> withCredentials: true

### ISSUE THREAD

**Issue by giggioz** [wyuenho/backgrid-paginator#43]
Hi, how can i add the option xhrFields: { withCredentials: true} to the ajax call when i click on the paginator's link?

![image](https://cloud.githubusercontent.com/assets/6266740/10360543/c665560a-6da1-11e5-8e2c-d47495576a69.png)

Thanks.

**Comment by wyuenho** [comment]
Override the collection's fetch method to pass a data option to jquery.
