### ISSUE TITLE
Publish 0.3.6 version to NPM

### ISSUE THREAD

**Issue by swillard-r7** [wyuenho/backgrid-paginator#45]
Any chance you could cut a new release and publish to NPM? I'm looking to grab the latest commits in master and I'd prefer not to depend on a commit SHA version in my package.json. Thanks!

**Comment by amenadiel** [comment]
For some reason, the version in NPM is 0.3.7. How is that even possible? There's no such tag, and even master's package.json reports version 0.3.5

**Comment by swillard-r7** [comment]
Maybe someone increased the version locally, and then did an `npm publish` without committing that change. But yeah, it's pretty strange.

**Comment by wyuenho** [comment]
Let's just say there are more fun things on npm than left-pad :)

I just got collab access to that npm package recently. I haven't updated backgrid-paginator yet. I intend on updating this and backgrid-select-all really really really really soon.

**Comment by Charca** [comment]
Hey @swillard-r7 mea culpa! The latest and greatest is on npm now, and version numbers are now consistent between the repo and the package. See #46 for more info.
