### ISSUE TITLE
Inconsistent repos and versions

### ISSUE THREAD

**Issue by amenadiel** [wyuenho/backgrid-paginator#46]
I kept noticing that in the current repo, which is the official one, it tagged as version 0.3.5. [package.json](https://github.com/wyuenho/backgrid-paginator/blob/0.3.5/package.json) reports the same version.

However, when I install this plugin with npm, [it installs version 0.3.7](https://www.npmjs.com/package/backgrid-paginator). It turns out @charca has publishing permissions at npm, so the version we're installing is [Charca/backgrid-paginator@master](https://github.com/Charca/backgrid-paginator). 

This is really confusing. The differential commits should have been merged in here, or the repo URL should have been updated at NPM, and either way, version 0.3.7 should be tagged. 

What should we do? I'm willing to help, so if you're willing to give me contributor access in here or npm, I can sort things out to restore consistency across repos and package managers.

**Comment by wyuenho** [comment]
cc @charca

**Comment by Charca** [comment]
Hey @amenadiel, I've just updated the repo to match the version on my fork (that is currently published on npm), and pushed the tags to keep it consistent. New releases of the npm packages will be published from this repo going forward to avoid confusion. Sorry for the trouble there, totally my fault.
