### ISSUE TITLE
Maybe it's better to delete dependency from Backgrid library.

### ISSUE THREAD

**Issue by nekitozzz** [wyuenho/backgrid-paginator#49]
As I can see only dependency is backbone.paginator, not Backgrid library. So why this paginator require Backgrid?

**Comment by wyuenho** [comment]
Because this is a backgrid extension

https://github.com/wyuenho/backgrid-paginator/blob/master/backgrid-paginator.js#L70

**Comment by nekitozzz** [comment]
@wyuenho Yes, but it can be easily deleted, so people can use it without Backgrid, only with backbone.paginator.
